stages:
  - quality_checks
  - integration_tests
  - publish

image: rust:buster

lint:
  stage: quality_checks
  script:
    - rustup component add clippy
    - cargo clippy

unit_test:
  stage: quality_checks
  script:
    - cargo test

browser_integration_test:
  stage: integration_tests
  script:
    - apt-get update
    - apt-get install firefox-esr -y
    - cargo install wasm-pack
    - wasm-pack test --headless --firefox

npm_publish:
  stage: publish
  script:
    - apt-get update
    - apt-get install curl
    - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
    - apt-get install -y nodejs
    - echo _auth=${NPM_ACCESS_TOKEN} >> .npmrc
    - echo email=${NPM_EMAIL} >> .npmrc
    - echo always-auth=true >> .npmrc
    - wasm-pack build
    - wasm-pack pack
    - wasm-pack publish
#  only:
#    - main