stages:
  - quality

image: rust:buster

lint:
  stage: quality
  script:
    - rustup component add clippy
    - cargo clippy

unit_test:
  stage: quality
  script:
    - cargo test

browser_integration_test:
  stage: quality
  script:
    - cargo install wasm-pack
    - wasm-pack test --headless --firefox