stages:
  - quality

image: node:16-alpine

cache:
  paths:
    - node_modules/

test:
  stage: quality
  script:
    - npm install
    - npm run test

lint:
  stage: quality
  script:
    - npm install
    - npm run lint