stages:
  - quality_checks
  - integration_tests

image: rust:buster

lint:
  stage: quality_checks
  script:
    - rustup component add clippy
    - cargo clippy

unit_test:
  stage: quality_checks
  script:
    - cargo test

browser_integration_test:
  stage: integration_tests
  script:
    - cargo install wasm-pack
    - wasm-pack test --headless --firefox